mutation CreateUser($password: String!, $username: String!, $email: String!) {
  createUser(password: $password, username: $username, email: $email) {
    ... on User {
      id
      username
      email
    }
    ... on BaseError {
      message
    }
  }
}
