mutation Login($username: String!, $password: String!) {
  login(username: $username, password: $password) {
    ... on LoginToken {
      token
    }
    ... on BaseError {
      message
    }
  }
}
