mutation Login($username: String!, $password: String!) {
  login(username: $username, password: $password) {
    ... on LoginData {
      sessionId
      userId
    }
    ... on BaseError {
      message
    }
  }
}
