query FindLoggedInUser {
  findLoggedInUser {
    ... on User {
      id
      bio
      username
      sessionId
      email
      createdAt
      avatarUrl
    }
    ... on UnknownError {
      message
    }
  }
}
